apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
  namespace: graces-3-tier-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      initContainers:
      - name: wait-for-first
        image: busybox
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres-service; sleep 2; done;']
      containers:
      - name: api-container
        image: disgraceful/3-tier-application:api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: ConnectionStrings__Basic3Tier
            value: "Host=postgres-service;Port=5432;Database=basic3tier;Username=postgres;Password=admin123"
