version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: basic3tier
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - 3tier

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-container
    ports:
      - 90:80
    depends_on:
      - postgres
    environment:
      ConnectionStrings__Basic3Tier: "Host=postgres;Port=5432;Database=basic3tier;Username=postgres;Password=admin123"
    networks:
      - 3tier

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui-container
    ports:
      - 82:80
    networks:
      - 3tier
    depends_on:
      - api
      - postgres

volumes:
  postgres_data:

networks:
  3tier:
    driver: bridge
